version: '3.8'

services:
  node-app:
    build: .
    container_name: node-app
    ports:
      - "4881:4881"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - my-redis-node-app-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4881"]
      interval: 30s
      retries: 3
      start_period: 10s

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "8001:8001"    # Redis Stack Web UI
      - "6379:6379"    # Standard Redis port
    networks:
      - my-redis-node-app-network
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      retries: 3
      start_period: 10s

networks:
  my-redis-node-app-network:
    driver: bridge
